Add result of 2020-2021, 2021-2022
tkbpc/tkbpc.github.io pull request #1
Opened 2024-06-17 11:12 UTC by oshamashama

成績を追加しました(全部ではない)

2024-06-17 11:43 UTC, oshamashama commented
そのうちフォーマットしたいね

2024-06-17 11:47 UTC, oshamashama commented
フォーマットしました

2024-06-17 14:24 UTC, oshamashama commented
format は別でやった方が良い気がしたので revert しました．後程やります．
@kichi2004 レビュー・マージお願いします．

2024-07-05 17:26 UTC, kichi2004 requested changes

2024-07-05 17:26 UTC, kichi2004 commented on results.html
> +									<tr><th>年度</th><th>チーム名</th><th>国内予選</th><th colspan="2">アジア地区予選</th><th colspan="2">Play Off</th><th colspan="2">World Finals</th></tr>
```suggestion
									<tr><th>年度</th><th>チーム名</th><th>国内予選</th><th colspan="2">アジア地区予選</th><th colspan="2">Playoff</th><th colspan="2">World Finals</th></tr>
```
Playoff が正しい表記っぽいです
https://icpc.iisf.or.jp/asia-pacific/asia-pacific-championship-2024/

2024-07-05 17:31 UTC, kichi2004 approved these changes

2024-07-05 17:33 UTC, merged